-- This file was automatically generated by 'hspec-discover'
-- and will be overwritten on subsequent runs.
-- To make changes, edit the test spec files directly.

{-# OPTIONS_GHC -F -pgmF hspec-discover #-}

